name: app
description: "FlutterKaigi 2025 Conference Application"
publish_to: "none"
version: 1.2.0

environment:
  sdk: ^3.10.0-209.1.beta
  flutter: ^3.38.0-0.1.pre

resolution: workspace

dependency_overrides:
  go_router: ^16.2.1
  grpc: 4.2.0

dependencies:
  auth_client:
    path: ../../packages/auth_client
  bff_client:
    path: ../../packages/bff_client
  collection: ^1.19.1
  crop_your_image: ^2.0.0
  cupertino_icons: ^1.0.8
  db_types:
    path: ../../packages/db_types
  dio: ^5.8.0+1
  faker: ^2.2.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_sticky_header: ^0.8.0
  flutter_svg: ^2.2.1
  flutter_web_plugins:
    sdk: flutter
  flutterrific_opentelemetry: ^0.3.4
  font_awesome_flutter: ^10.10.0
  freezed_annotation: ^3.0.0
  go_router: ^16.2.1
  hooks_riverpod: ^3.0.0-dev.17
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^7.1.3
  opentelemetry:
    git:
      url: https://github.com/Workiva/opentelemetry-dart.git
      ref: 0f79893efeda4d096a8f7f85b4cdbec6e7ea0179
  package_info_plus: ^9.0.0
  path: ^1.9.1
  pub_semver: ^2.1.4
  qr_flutter: ^4.1.0
  riverpod_annotation: ^3.0.0-dev.17
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker_dio_logger: ^5.0.0
  talker_flutter: ^5.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  flutterkaigi_lints:
    path: ../../packages/flutterkaigi_lints
  freezed: ^3.0.6
  go_router_builder: ^4.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  slang_build_runner: ^4.8.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - res/assets/
    - res/assets/sns/dark/
    - res/assets/sns/light/
    - res/assets/fonts/NotoSansJP/
    - res/assets/fonts/NotoSansMono/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: res/assets/fonts/NotoSansJP/NotoSansJP-VariableFont.ttf
    - family: NotoSansMono
      fonts:
        - asset: res/assets/fonts/NotoSansMono/NotoSansMono-VariableFont.ttf

  config:
    enable-swift-package-manager: true
